import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building2, Camera, Check, UtensilsCrossed } from "lucide-react";
import Header from "../../../components/Header";
import Footer from "../../../components/Footer";
import JsonLd from "../../../components/JsonLd";
import { breadcrumbLd, webPageLd } from "../../../lib/seo";

export const metadata: Metadata = { title: "매장 사진촬영 가격표 | 음식점 · 공간 촬영", description: "음식점과 공간·펜션을 위한 매장 사진촬영 가격표입니다. 기본, 고급, 프리미엄 구성과 촬영 범위를 확인할 수 있습니다.", alternates: { canonical: "https://www.harangmarketing.com/services/photo/price" } };
const PLANS = [
  { name: "기본", price: "700,000", time: "180분", days: "5일", revisions: "2회", food: "메뉴 A컷 30장 · B컷 30장", stay: "시설 A컷 30장 · B컷 30장", note: "60평 이하 기준" },
  { name: "고급", price: "1,000,000", time: "210분", days: "7일", revisions: "2회", food: "메뉴 A컷 50장 · B컷 50장", stay: "시설 A컷 50장 · B컷 50장", note: "60평 이하 기준" },
  { name: "프리미엄", price: "1,200,000", time: "300분", days: "9일", revisions: "2회", food: "메뉴 A컷 60장 · B컷 60장", stay: "시설 A컷 60장 · B컷 60장", note: "넓은 공간 포함 기준" },
] as const;
const VERSIONS = [{ title: "음식점·요식업", description: "메뉴, 상차림, 매장 동선을 중심으로 촬영합니다.", icon: UtensilsCrossed, href: "/services/photo/food" }, { title: "공간·펜션", description: "객실, 공용공간, 외부 동선과 머무는 장면을 중심으로 촬영합니다.", icon: Building2, href: "/services/photo/stay" }] as const;

export default function PhotoPricePage() { return <><Header /><main className="pt-[104px] md:pt-[108px] bg-gray-50"><JsonLd data={webPageLd({ path: "/services/photo/price", name: "매장 사진촬영 가격표", description: "음식점과 공간·펜션 사진촬영의 기본, 고급, 프리미엄 가격표" })} /><JsonLd data={breadcrumbLd([{ name: "홈", path: "/" }, { name: "서비스", path: "/services" }, { name: "매장 사진촬영", path: "/services/photo" }, { name: "가격표", path: "/services/photo/price" }])} />
  <section className="bg-gray-950 py-14 md:py-20"><div className="max-w-6xl mx-auto px-4 md:px-6 lg:px-8"><div className="inline-flex items-center gap-2 rounded-full border border-white/15 px-3 py-1.5 text-xs font-semibold text-blue-300 mb-5"><Camera size={14} /> 매장 사진촬영 가격표</div><h1 className="max-w-3xl text-3xl md:text-5xl font-black leading-tight text-white">찍을 범위와 남길 컷을<br />처음부터 정합니다</h1><p className="max-w-2xl mt-5 text-base md:text-lg leading-relaxed text-gray-300">음식점과 공간 촬영은 같은 가격 구성을 사용하되, 촬영 전 확인하는 컷 목록과 진행 순서는 다르게 잡습니다.</p></div></section>
  <section className="py-12 md:py-16 bg-white"><div className="max-w-6xl mx-auto px-4 md:px-6 lg:px-8"><div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-10">{VERSIONS.map(({ title, description, icon: Icon, href }) => <Link key={title} href={href} className="group rounded-2xl border border-gray-200 bg-gray-50 p-5 md:p-6 shadow-sm transition-colors hover:border-blue-300 hover:bg-blue-50"><div className="flex items-start justify-between gap-4"><div><div className="w-10 h-10 rounded-xl bg-blue-600 text-white flex items-center justify-center mb-4"><Icon size={19} /></div><h2 className="text-lg font-black text-gray-900">{title}</h2><p className="mt-2 text-sm leading-relaxed text-gray-600">{description}</p></div><ArrowRight size={18} className="mt-1 text-blue-600 group-hover:translate-x-0.5 transition-transform" /></div></Link>)}</div><div className="flex items-end justify-between gap-4 mb-6"><div><p className="text-xs font-bold tracking-[0.16em] text-blue-600 mb-3">PRICE GUIDE</p><h2 className="text-2xl md:text-3xl font-black text-gray-900">촬영 구성별 가격</h2></div><p className="hidden sm:block text-sm text-gray-500">부가세 별도</p></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{PLANS.map((plan, index) => <article key={plan.name} className={`rounded-2xl border bg-white p-5 md:p-6 shadow-sm ${index === 1 ? "border-blue-500 ring-1 ring-blue-500" : "border-gray-200"}`}>{index === 1 && <p className="text-xs font-bold text-blue-600 mb-4">가장 많이 고르는 구성</p>}<h3 className="text-xl font-black text-gray-900">{plan.name}</h3><p className="mt-4 text-3xl font-black text-gray-900">{plan.price}<span className="ml-1 text-base font-bold">원</span></p><p className="mt-1 text-xs text-gray-500">부가세 별도</p><div className="my-6 h-px bg-gray-100" /><ul className="space-y-3 text-sm text-gray-700"><li className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-blue-600" />보정 작업은 A컷 기준</li><li className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-blue-600" />음식점 {plan.food}</li><li className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-blue-600" />공간·펜션 {plan.stay}</li><li className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-blue-600" />촬영 {plan.time} · 작업 {plan.days}</li><li className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-blue-600" />수정 {plan.revisions} · {plan.note}</li></ul><Link href={`/contact?industry=사진촬영&plan=${encodeURIComponent(plan.name)}`} className="mt-7 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-gray-900 px-4 py-3 text-sm font-bold text-white hover:bg-gray-800">{plan.name} 상담 신청 <ArrowRight size={15} /></Link></article>)}</div><p className="mt-6 text-xs leading-relaxed text-gray-500">표에 적힌 촬영 시간, 컷 수, 작업일은 기본 구성입니다. 이동 거리, 추가 촬영 공간, 모델 섭외, 채널별 등록 작업은 사전 협의한 범위에 따라 별도로 안내합니다.</p></div></section>
</main><Footer /></>; }
